# Generated by Django 3.0.6 on 2020-05-21 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='hotelrooms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.IntegerField()),
                ('hotel_id', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
